apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyter-singleuser-profiles
data:
  jupyterhub-singleuser-profiles.yaml: |
      profiles:
      - name: globals
        env:
          - name: S3_ENDPOINT_URL
            value:
        resources:
          requests:
            memory: 6Gi
            cpu: 1m
          limits:
            memory: 12Gi
            cpu: 4
