apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudbeaver
spec:
  template:
    spec:
      containers:
        - name: cloudbeaver
          resources:
            limits:
              cpu: "4"
              memory: 6Gi
            requests:
              cpu: "2"
              memory: 4Mi
