apiVersion: kustomize.config.k8s.io/v1beta1
components:
    - ../../../../components/limitranges/default
    - ../../../../components/resourcequotas/medium
kind: Kustomization
namespace: okd-centos
resources:
    - namespace.yaml
