apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: odh-admin
users:
  - 4n4nd
  - accorvin
  - anishasthana
  - codificat
  - crobby
  - hemajv
  - humairak
  - HumairAK
  - lavlas
  - LaVLaS
  - maulikjs
  - nakfour
  - rimolive
  - tumido
  - vpavlin
